#!/bin/bash

TYPE="stars"

if [ -f "/home/chronos/user/work/misc/matrix/$1.sh" ]; then
	TYPE=$1
fi

if [ -f /home/chronos/user/work/misc/screensaver.on ] || [ $1 ]; then
	bash "/home/chronos/user/work/misc/matrix/$TYPE.sh"
	# cmatrix -ab -u4 -M "\C<\Wchronos\C@\Wragnarok\C>\W   \h\C:\W\m  \b\C%"
else
	echo -e "\033[33mlogout \033[0m@ \033[36m`TZ=America/New_York date +%H:%M\ %d/%m` `batper`%\n\033[0m"
	read -p "$ "
fi
